# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5212a6756c7157ade5a6e09dda051bbb808d5179bba95550abbee417fd395c0bc82f97b2395463e83b6acc832ce8eadc10a17c0b87d81c7ec51afc01047a7064

test:
  secret_key_base: 7155cce9273c54e2ea1f0cfe805f7c11053415c74e214bc1b4330de9ebf2ce9df1ad0688c1810d0dc5c93f0e46687292da3a8e60e975d0404c0cca49d1994d05

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
